version: "2"

services:
  vote:
    build: ./vote
    command: python app.py
    ports:
      - "80:80"

  redis:
    image: redis:alpine
    ports: ["6379"]

  worker:
    build: ./worker

  db:
    image: postgres:9.4
    ports:
      - "5432:5432"

  result:
    build: ./result
    ports:
      - "8080:80"
